### ISSUE TITLE
If no page found in the website.

### ISSUE THREAD

**Issue by skx6** [desertfury/flask-opencv-streaming#4]
I opened the project with Pycharm and run app.py, but found nothing in http://0.0.0.0:5000. So I tried to change the last line in app.py:     app.run(host='0.0.0.0', debug=True, threaded=True, port=8080) and searched the website http://127.0.0.1:8080/ and finally succeed.

**Comment by desertfury** [comment]
Hello!
Thank you for your contribution! Could you elaborate more on this issue? 
```$ python3 app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 101-116-657
127.0.0.1 - - [13/Feb/2020 18:33:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [13/Feb/2020 18:33:04] "GET /video_feed HTTP/1.1" 200 -
127.0.0.1 - - [13/Feb/2020 18:33:05] "GET /favicon.ico HTTP/1.1" 404 -
```

This is what flask is printing to standart input when i ran the app, could you tell me what os do you use and the version of Flask?
